typography_spectrum: 0.597066265065223
content_rating:
  adult: false
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.15643940097652376
  lightness: 0.6531669232062995
  saturation: 0.38199757458642125
  rhythmicContrast: 0.43281447631306946
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5226020296104252
analytics:
  google: null
  facebook: null
  twitter: null
name: Discus Solutions
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Menu
    url: 'http://www.discus.solutions/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a88c83a1-0044-4ed1-bd23-d775d178659a.png
title: We Deliver..
purpose: []
