typography_spectrum: 0.597066265065223
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.15643940097652376
  lightness: 0.6531669232062995
  saturation: 0.38199757458642125
  rhythmicContrast: 0.43281447631306946
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5226020296104252
analytics:
  google: null
  facebook: null
  twitter: null
name: Discus Solutions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: We Deliver..
purpose: []
